### ISSUE TITLE
Italic style is applied to certain types of callouts even when all preset css is disabled

### ISSUE THREAD

**Issue by joelatschool** [RyotaUshio/obsidian-math-booster#202]
I'm using beta9 and I noticed that somehow the rule linked below:

https://github.com/RyotaUshio/obsidian-math-booster/blob/6f20179380552398001877361076951a7d278e06/styles/framed.css#L21

Is generating a CSS rule
```css
:not(theorem-callout-axiom):not(.theorem-callout-definition):not(.theorem-callout-remark).theorem-callout-en .callout-content {
    font-style: italic;
}
```
which does not target `.theorem-callout-framed`.
